Enhance `kytos_stats`
kytos-ng/kytos-end-to-end-tests pull request #253
Opened 2023-08-02 18:03 UTC by gretelliz

Closes #243 

### Summary

Add `test_036_table_1_active_count_update` test to create some traffic on table 1, and  make sure that the stats are accurate.

Update `test_015_packet_count` and `test_020_bytes_count` tests to avoid trying to find a non-empty flow, instead a flow is installed and query it later for stats.

2023-08-14 15:42 UTC, viniarck commented on tests/test_e2e_70_kytos_stats.py
> +        assert '00:00:00:00:00:00:00:01' in data, str(data)
Typically we only add extra context to the assert messages when pytest doesn't add much info given a boolean comparison like `len(data) == 1`. For instance, in a string `in` assertion it typically includes, even in older version of pytest:

```
E       AssertionError: assert 'a' in 'some'
```

The extra content won't cause harm though, but if we don't have too then we're just adding unnecessary information, can you simulate an assertion error for this equivalent case and see if it's really needed?

2023-08-14 15:47 UTC, viniarck commented on tests/test_e2e_70_kytos_stats.py
> +        payload = {"flows": [{"cookie": cookie, "packet_count": 8, "duration_sec": 2}]}
packet_count and duration_sec shouldn't be sent, it doesn't cause any issues (now), but can get confusing for anyone else reading this in the future, can you review this?

2023-08-14 15:52 UTC, viniarck reviewed
The augmented coverage looks good to me. I'll leave it up to @italovalcy to approve though since you both have been discussing about this. Other than that, I raised a few minor points. Great PR, Gretel.

2023-08-14 15:59 UTC, gretelliz commented
@viniarck , Thank you.

2023-09-11 21:35 UTC, viniarck commented
@gretelliz check out with @italovalcy if this can already land, thanks.

2023-09-15 17:56 UTC, italovalcy requested changes
Hi @gretelliz thanks for sending the PR! All looks good to me. I've just added some suggestions regarding the inclusion of data-plane tests to also make sure the stats are being collected properly.

2023-09-15 17:56 UTC, italovalcy commented on tests/test_e2e_70_kytos_stats.py
> +        payload = {"flows": [{"cookie": cookie}]}
```suggestion
        payload = {
            "flows": [{
                "cookie": cookie,
                "match": {"in_port": 1, 'dl_dst': '33:33:00:00:00:02', 'dl_type': 0x86dd},
                'actions': [{'action_type': 'output', 'port': 2}]
            }]
        }
```

2023-09-15 17:56 UTC, italovalcy commented on tests/test_e2e_70_kytos_stats.py
> +        time.sleep(10)
```suggestion
        # wait the flow to be installed
        time.sleep(5)

        # send N packets, each one containing 1500 bytes
        # (14 ether hdr + 40 ipv6 + 8 icmp + 1438 payload)
        h11 = self.net.net.get('h11')
        n = 20
        h11.cmd(f"ping -6 -b -c {n} -s 1438 FF02::2%h11-eth0 -Mdo -i 0.01 -W 2")

        # give enough time for stats gathering (of_core.STATS_INTERVAL)
        time.sleep(10)
```

2023-09-15 17:56 UTC, italovalcy commented on tests/test_e2e_70_kytos_stats.py
> +        payload = {"flows": [{"cookie": cookie}]}
```suggestion
        payload = {
            "flows": [{
                "cookie": cookie,
                "match": {"in_port": 1, 'dl_dst': '33:33:00:00:00:02', 'dl_type': 0x86dd},
                'actions': [{'action_type': 'output', 'port': 2}]
            }]
        }
```

2023-09-15 17:56 UTC, italovalcy commented on tests/test_e2e_70_kytos_stats.py
> +        time.sleep(10)
```suggestion
        # wait the flow to be installed
        time.sleep(5)

        # send N packets, each one containing 1500 bytes
        # (14 ether hdr + 40 ipv6 + 8 icmp + 1438 payload)
        h11 = self.net.net.get('h11')
        n = 20
        h11.cmd(f"ping -6 -b -c {n} -s 1438 FF02::2%h11-eth0 -Mdo -i 0.01 -W 2")

        # waiting to give enough time for stats gathering (of_core.STATS_INTERVAL)
        time.sleep(10)
```

2023-09-15 17:56 UTC, italovalcy commented on tests/test_e2e_70_kytos_stats.py
> +                bytes_counter = flow['byte_count']
```suggestion
                bytes_counter = flow['byte_count']
                assert bytes_counter >= n*1500, str(flow)
```

2023-09-15 17:56 UTC, italovalcy commented on tests/test_e2e_70_kytos_stats.py
> +                packet_counter = flow['packet_count']
```suggestion
                packet_counter = flow['packet_count']
                assert packet_counter >= n, str(flow)
```

2023-09-20 15:43 UTC, gretelliz commented
Thank you, @italovalcy. Good suggestion for incorporating dataplane checks.

2023-09-20 16:11 UTC, viniarck approved these changes
@gretelliz looks like this PR is ready to land since you've also addressed @italovalcy's feedback. Please re-run this test suite if it's still passing that feel free to merge.

2023-09-25 15:17 UTC, merged

2023-09-25 15:36 UTC, gretelliz commented
> @gretelliz looks like this PR is ready to land since you've also addressed @italovalcy's feedback. Please re-run this test suite if it's still passing that feel free to merge.

```
tests/test_e2e_70_kytos_stats.py ........                                [100%]

=============================== warnings summary ===============================
test_e2e_70_kytos_stats.py: 17 warnings
  /usr/lib/python3/dist-packages/mininet/node.py:1121: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    return ( StrictVersion( cls.OVSVersion ) <

test_e2e_70_kytos_stats.py: 17 warnings
  /usr/lib/python3/dist-packages/mininet/node.py:1122: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    StrictVersion( '1.10' ) )

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
------------------------------- start/stop times -------------------------------
================== 8 passed, 34 warnings in 467.41s (0:07:47) ==================
```